ALTER TABLE batch MODIFY COLUMN name TEXT NULL;

ALTER TABLE course MODIFY  COLUMN name TEXT NULL;
ALTER TABLE course MODIFY  COLUMN description TEXT NULL;

ALTER TABLE institute MODIFY  COLUMN name TEXT NULL;
ALTER TABLE institute MODIFY  COLUMN logo TEXT NULL;
ALTER TABLE institute MODIFY  COLUMN email TEXT NULL;
ALTER TABLE institute MODIFY  COLUMN contact_number TEXT NULL;

ALTER TABLE schedule MODIFY  COLUMN topic TEXT NULL;
ALTER TABLE schedule MODIFY  COLUMN join_url TEXT NULL;
ALTER TABLE schedule MODIFY  COLUMN zoom_meeting_id TEXT NULL;
ALTER TABLE schedule MODIFY  COLUMN zoom_host_id TEXT NULL;

ALTER TABLE student MODIFY  COLUMN name TEXT NULL;
ALTER TABLE student MODIFY  COLUMN email TEXT NULL;
ALTER TABLE student MODIFY  COLUMN contact_number TEXT NULL;

ALTER TABLE subject MODIFY  COLUMN name TEXT NULL;

ALTER TABLE teacher MODIFY  COLUMN name TEXT NULL;
ALTER TABLE teacher MODIFY  COLUMN contact_number TEXT NULL;
ALTER TABLE teacher MODIFY  COLUMN email TEXT NULL;
ALTER TABLE teacher MODIFY  COLUMN subject TEXT NULL;

ALTER TABLE topic MODIFY  COLUMN name TEXT NULL;
ALTER TABLE topic MODIFY  COLUMN `description` TEXT NULL;

ALTER TABLE announcements MODIFY  COLUMN content TEXT NULL;

ALTER TABLE attachment MODIFY  COLUMN url TEXT NULL;
ALTER TABLE attachment MODIFY  COLUMN name TEXT NULL;

ALTER TABLE study_material MODIFY  COLUMN name TEXT NULL;

ALTER TABLE test MODIFY  COLUMN name TEXT NULL;
ALTER TABLE test MODIFY  COLUMN description TEXT NULL;

ALTER TABLE institute ADD about_us TEXT NULL;
ALTER TABLE institute ADD owner_name TEXT NULL;
ALTER TABLE institute ADD owner_email TEXT NULL;