steps:
  - name: gradle:6.3-jdk8
    entrypoint: gradle
    args: ["test"]
  - name: gradle:6.3-jdk8
    entrypoint: gradle
    args: ["assemble"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/randomchatservice", "--build-arg=JAR_FILE=build/libs/randomchatservice-1.0.jar", "."]
images: ["gcr.io/$PROJECT_ID/randomchatservice"]